# ==========================================================
# 自动启动：开机后你需要哪些“保镖”后台待命
# ==========================================================

# --- 基础工具栏 ---
exec-once = waybar &                     # 启动我们在上面配置的 Waybar 顶栏
exec-once = nm-applet --indicator &      # 启动网络连接的小图标（WiFi管理）
exec-once = blueman-applet &             # 启动蓝牙管理的小图标

# --- 权限与输入法 ---
exec-once = /usr/libexec/polkit-gnome-authentication-agent-1 & # 弹出输入密码的提权窗口
exec-once = fcitx5 -d                    # 以守护进程模式启动输入法

# --- 视觉增强与壁纸 ---
exec-once = hyprshade on vibrance        # 开启色彩增强滤镜，让屏幕颜色更鲜艳
exec-once = swww-daemon &                # 启动壁纸服务的底层引擎
exec-once = bash ~/.config/waybar/scripts/wallpaper_daemon.sh & # 运行我们写的随机壁纸脚本
# --- 通知 ---
exec-once = swaync
# --- 工作区 ---
