# ==========================================================
# 输入设置：键盘、鼠标、触控板的手感调节
# ==========================================================

input {
    kb_layout = us               # 键盘布局，大部分人都是美式键盘 (us)
    follow_mouse = 2             # 鼠标跟随逻辑：2 代表鼠标指过去，窗口不抢焦点
    
    touchpad {
        natural_scroll = true    # 自然滚动：像操作手机一样，双指往上拨页面往下滚
    }
}
# --- 禁用内置触摸板 ---
device {
    name = foca0001:00-2808:0106-touchpad
    enabled = false
}
