# ==========================================================
# 核心快捷键：用键盘掌控一切
# ==========================================================

$mainMod = SUPER                 # 将 Win 键定义为“神键”

# --- 启动软件 ---
bind = $mainMod, Q, exec, kitty                  # Win + Q: 打开黑乎乎的终端
bind = $mainMod, E, exec, thunar                 # Win + E: 打开文件夹
bind = $mainMod, R, exec, hyprlauncher           # Win + R: 寻找你要用的软件

# --- 窗口控制 ---
bind = $mainMod, C, killactive,                  # Win + C: 关掉当前这个不听话的窗口
bind = $mainMod, V, togglefloating,              # Win + V: 让窗口在屏幕上到处乱飞（浮动）
bind = $mainMod, P, pseudo,                      # Win + P: 假平铺（保持原始比例）
bind = $mainMod, J, togglesplit,                 # Win + J: 改变切割方向（横着切还是竖着切）
bind = $mainMod, M, exit,                        # Win + M: 退出 Hyprland，回到登录界面

# --- 鼠标互动 ---
bindm = $mainMod, mouse:272, movewindow          # Win + 鼠标左键：拖拽窗口位置
bindm = $mainMod, mouse:273, resizewindow        # Win + 鼠标右键：拉大或缩小窗口

# ==========================================================
# 动态工作区管理 (告别 1, 2, 3 数字键)
# ==========================================================

# Win + N: 跳转到一个全新的空工作区
bind = $mainMod, N, workspace, empty

# Win + Shift + N: 把当前窗口直接扔到一个全新的空工作区，并跟过去
bind = $mainMod SHIFT, N, movetoworkspace, empty

# --- 方案 A：用键盘左右切换 ---
# Win + [ 和 Win + ]：在上一个/下一个工作区之间来回切换
#bind = $mainMod, bracketleft, workm+1ce, r-1
#bind = $mainMod, bracketright, workspace, r+1

# 或者用常用的 Win + Tab：
#bind = $mainMod, Tab, workspace, r+1
#bind = $mainMod SHIFT, Tab, workspace, r-1

# --- 方案 B：用鼠标滚轮无缝滑动 (推荐) ---
# 按住 Win 键，滚动鼠标滚轮，就可以在现有的工作区之间丝滑切换
bind = $mainMod, mouse_down, workspace, r+1
bind = $mainMod, mouse_up, workspace, r-1
