# ==========================================================
# 硬件适配与杂项：解决一些琐碎但重要的事
# ==========================================================

# --- 显示器设置 ---
# eDP-1 是你的主屏，preferred 代表最高分辨率，auto 代表位置自动，1.6 代表放大 1.6 倍
monitor=eDP-1,preferred,auto,1.67

# --- XWayland 兼容性 (防止部分老软件变糊) ---
xwayland {
    force_zero_scaling = true   # 强制 XWayland 软件不进行额外缩放，保持清晰
}

# --- 杂项设定 ---
misc {
    disable_hyprland_logo = true    # 彻底关掉开机时那个紫色的 Logo
    force_default_wallpaper = 0     # 强制禁用内置壁纸，把舞台留给我们的 swww 脚本
    disable_splash_rendering = true # 关掉底部的欢迎文字
}
